### ISSUE TITLE
DOI is treated as a required section in edit page

### ISSUE THREAD

**Issue by mauzey1** [aims-group/publication-site#102]
When I tried to edit an entry I made that didn't have a DOI listed, it would not allow me to submit the changes until I filled out the DOI section.  If we are allowed to submit entries without a DOI, then shouldn't we be allowed to edit these entries without needing to submit a DOI?

**Comment by taylor13** [comment]
Yes, I'd say definitely that makes sense to me.

**Comment by mauzey1** [comment]
I have added the commit https://github.com/aims-group/publication-site/commit/4de260c63df205091f42da1e5b680e64048aea90 that makes the DOI section no longer required when editing a publication that doesn't have the status "Published".  These changes are now live on the test server.
