### ISSUE TITLE
AGU EOS articles incorrectly identified

### ISSUE THREAD

**Issue by durack1** [aims-group/publication-site#103]
The publication linked off https://doi.org/10.1029/2018EO101751 which is published as:

**Durack, Paul J.**, **Karl E. Taylor**, Veronika Eyring, **Sasha K. Ames**, **Tony Hoang**, **Denis Nadeau**, **Charles Doutriaux**, Martina Stockhause and **Peter J. Gleckler** (2018) Toward standardized data sets for climate model experimentation. Eos, Transactions, American Geophysical Union, 99. DOI: 10.1029/2018EO101751

Is incorrectly identified as the journal "Advances in Geosciences", see below:
![Screenshot_2020-07-16 New Publication](https://user-images.githubusercontent.com/3229632/87702071-c8977600-c74d-11ea-8634-b3a01fd3120d.png)

**Comment by taylor13** [comment]
Just curious, did I enter the wrong journal name?  Did Paul? Did it get harvested using the DOI?  Can't Paul just edit it to correct it?

**Comment by durack1** [comment]
@taylor13 that is what was automagically populated when I entered the DOI, so our journal name harvesting is incorrect

**Comment by mauzey1** [comment]
The problem appears to be that the process that matches the title from the link, `Eos`, with a journal name in the list is finding anything that has the `eos` substring in it like `Advances in Geoscience`.  `EOS, Transactions` is also one of the matches but `Advances in Geoscience` is the first match that is taken.  If I add `Eos` to the journal list, it will find that name since it is a direct match.

One way to resolve this issue is to add `EOS` to the journal list, and make the matching of the journal title case insensitive since the title in the JSON from the link is `Eos`.

Are `EOS` and `EOS, Transactions` the same thing?

**Comment by taylor13** [comment]
thanks for getting to the root of the problem.  Is there a way we can check what the journal name returned by the doi will invariably be and set the name in our list to exactly match that (assuming the doi will always return the same value).

**Comment by durack1** [comment]
Normally a doi will be aligned with a publication, so for e.g. Nature journals have a prefix 10.1038/, and Science journals have 10.1126/, that would be something we could key off

**Comment by taylor13** [comment]
This should probably be fixed sooner, rather than later.  @durack1 do you agree?

**Comment by durack1** [comment]
@taylor13 agreed, the more bugs we can stomp out before we get a huge user interest the better

**Comment by mauzey1** [comment]
I think this issue can be resolved by making the names in the journal list be more consistent with the name of the journal that appears in the "container-title" attribute of the DOI JSON.  The name of the journal for https://doi.org/10.1029/2018EO101751 should be `Eos` not `EOS, Transactions`.

Using the DOI prefix may not guarantee that the name of the journal will not change over time.  If we added an article from a journal with a DOI prefix that had a different journal name in the past, then that article would get mistaken as being from that journal.  By adding new journal names to the list, we can keep up with journal name changes while retaining legacy names for previously submitted articles.

I have noticed other issues with the names currently in the list.  There is a journal called `Chines Science bulletin` in the list.  I couldn't find that journal but I assume it should be `Chinese Science Bulletin`.  Although, according to this [wiki article](https://en.wikipedia.org/wiki/Science_Bulletin), the journal is now called `Science Bulletin`.

**Comment by taylor13** [comment]
I hadn't thought about Journals changing their name.  I don't think it happens often, but I guess it sometimes does.  (I think Eos was formerly known as "Eos, Transactions, American Geophysical Union".)

Will your approach be able to distinguish between "eos" in "Eos" and "eos"  in "Advances in Geosciences", which was the problem noted in https://github.com/aims-group/publication-site/issues/103#issue-658395042 ?

**Comment by mauzey1** [comment]
@taylor13 If the exact name of the journal is found in the list, then the site won't attempt find names in the same way that lead to the incorrect result.

**Comment by taylor13** [comment]
O.K.  then I can't think of any problems with what you propose.
thanks.

**Comment by durack1** [comment]
If we wanted to be really bulletproof here we could also use a DOI prefix, so 10.1029 for `Eos` for e.g. that way we can text match AND DOI prefix match which in most cases will perfectly resolve
