### ISSUE TITLE
BibTex links not showing up for publications that load after scrolling down.

### ISSUE THREAD

**Issue by mauzey1** [aims-group/publication-site#104]
The BibTex links for publications are not showing up when scrolling down the page.
![Screenshot_2020-07-23 Publication Hub](https://user-images.githubusercontent.com/42009431/88352681-79ce7b00-cd0f-11ea-987d-81e86744b6d7.png)

**Comment by taylor13** [comment]
Do we know that *all* references should have BibTex links?    I'm not familiar with BibTex, so can't advise.

**Comment by mauzey1** [comment]
@taylor13 The BibTex links are what display the citation info of the publications in [BibTex format](http://www.bibtex.org/Format/).  They don't link to anything external, they just run Javascript that formats the publication info.
![Screenshot_2020-07-23 Publication Hub](https://user-images.githubusercontent.com/42009431/88355566-e9496800-cd19-11ea-98f1-f39d5254b5cd.png)

**Comment by taylor13** [comment]
Got it.  So looks like we've got a problem.
thanks.
