### ISSUE TITLE
How do I add a journal not on your list?

### ISSUE THREAD

**Issue by mfwehner** [aims-group/publication-site#106]
My journals are not on the list. Other is not particularly informative...

**Comment by mauzey1** [comment]
@mfwehner 
We are currently in the process of updating the publication site, which will include instructing users on how to add journals to the list.  We have more details at #92.  These updates are currently in development and have yet to be pushed into production.

**Comment by taylor13** [comment]
Hi Michael,
Why don't you tell us the journal name(s) and we'll add them for the next release.
thanks.

**Comment by mfwehner** [comment]
Add two
Weather and Climate Extremes
Advances in Statistical Climatology, Meteorology and Oceanography

(I started the latter one).

Hope all is well.
M
