### ISSUE TITLE
Please add journal named: Scientific Reports.

### ISSUE THREAD

**Issue by lujunyubyyl** [aims-group/publication-site#128]
Please add journal named: Scientific Reports.

**Comment by taylor13** [comment]
I agree; this should be added.   Thanks.

**Comment by durack1** [comment]
@lujunyubyyl just to confirm this is Nature Scientific Reports (https://www.nature.com/srep/) correct?

**Comment by lujunyubyyl** [comment]
> @lujunyubyyl just to confirm this is Nature Scientific Reports (https://www.nature.com/srep/) correct?

Yes, it is correct. Thank you for your help!

**Comment by taylor13** [comment]
That's what I assumed.  I think that it is supposed to be cited as "Scientific Reports" (without the "Nature"), but I'm not positive.
