### ISSUE TITLE
Add LLNL/DOE standard footer

### ISSUE THREAD

**Issue by durack1** [aims-group/publication-site#134]
It seems that to meet the LLNL/DOE requirements we need to add a footer, as per [llnl.gov](www.llnl.gov)
![Screen Shot 2021-06-08 at 9 40 43 AM](https://user-images.githubusercontent.com/3229632/121224994-ee35de00-c83d-11eb-9c5d-ba1981a2efaf.png)

Another option is the "light" footer from [nexo.llnl.gov](nexo.llnl.gov)
![Screen Shot 2021-06-08 at 10 26 50 AM](https://user-images.githubusercontent.com/3229632/121230531-35bf6880-c844-11eb-9605-d0790102fc32.png)

@mauzey1 is this doable fairly easily?

@taylor13

**Comment by mauzey1** [comment]
@durack1 

Here is a footer that I have been working on.  It stays on the bottom of the browser window so that it doesn't get buried by the infinite scroll.
![Screenshot 2021-06-08 at 10-00-37 Publication Hub](https://user-images.githubusercontent.com/42009431/121227699-b8debf80-c840-11eb-9879-e9d68c0c6a4a.png)

**Comment by durack1** [comment]
@mauzey1 great start, I wonder if we should iterate with Rose/Amanda to get "sign off"?

**Comment by durack1** [comment]
@mauzey1 let's go with two lines

[Lawrence Livermore National Laboratory](https://www.llnl.gov/about), Livermore, CA 94550 | [Privacy & Legal Notice](https://www.llnl.gov/disclaimer) 
LLNL-WEB-XXXXXX | Prepared by LLNL under Contract DE-AC52-07NA27344

@taylor13 agree?

**Comment by durack1** [comment]
I agree with @taylor13 and had suggested

Please report any problems on our [Github Issues page](https://github.com/aims-group/publication-site/issues).
[Lawrence Livermore National Laboratory](https://www.llnl.gov/about), Livermore CA 94550 | [Privacy & Legal Notice](https://www.llnl.gov/disclaimer) | LLNL-WEB-XXXXXX  |  Prepared by LLNL under Contract DE-AC52-07NA27344

**Comment by durack1** [comment]
@mauzey1 reopening to await the IM number landing.

Also it'd be great if we can update the footer links with `<a href="$URL" target="_blank">$DISPLAYTEXT</a>` just so that folks clicking those links don't fall off the page

**Comment by durack1** [comment]
@mauzey1 I don't have perms to reopen, so feel free to do so
