### ISSUE TITLE
Publication DOI is not removed from pending DOI list if it is being submitted after a required fields warning

### ISSUE THREAD

**Issue by mauzey1** [aims-group/publication-site#138]
How to replicate:

1. Submit a publication DOI through the `Add Many Publications` option.
2. Process the DOI by clicking on `Pending` -> `Process Pending Items`.
3. Submit the publication without required info, such as not selecting CMIP5 or CMIP6.  This will cause the form to reload with a warning that the required fields need to be filled.
4. Fill the required fields and submit it again.  This will submit the publication to the database but will not remove it from the list of pending DOIs.  This will lead to the submission form reloading with the already-submitted publication DOI.

The current work around is to either skip to the next DOI, or click on `Pending` -> `View Pending Items` and manually remove the submitted DOI.

**Comment by taylor13** [comment]
Thanks for catching this.  If you need feedback from Paul or me, let us know.
