### ISSUE TITLE
Please add journal named: Sustainability

### ISSUE THREAD

**Issue by AmirrezaMorhedBozorgdel** [aims-group/publication-site#168]

**Comment by durack1** [comment]
@AmirrezaMorhedBozorgdel is this the correct journal? https://www.mdpi.com/journal/sustainability

**Comment by AmirrezaMorhedBozorgdel** [comment]
​Hi, yes it is correct.
Thank you for your time.
Amir

On Mon, 15 Farvardin 1401 11:19 PM, "Paul J. Durack" ***@***.***> wrote:
> 
@AmirrezaMorhedBozorgdel is this the correct journal? https://www.mdpi.com/journal/sustainability
