### ISSUE TITLE
Add PCMDI analytics to site

### ISSUE THREAD

**Issue by durack1** [aims-group/publication-site#172]
It would be great to implement analytics on this site, ala https://github.com/PCMDI/pcmdi.github.io/issues/431

It seems we only have matomo:
```
<!-- LLNL Analytics -->
    <script src="[/static/js/matomo.js](view-source:https://cmip-publications.llnl.gov/static/js/matomo.js)"></script>
```

**Comment by mauzey1** [comment]
@durack1 So you want to use the [same script we are using for Google Analytics on pcmdi.llnl.gov](https://github.com/PCMDI/pcmdi.github.io/blob/50f4179e0d00eeca088353d0bc59255bc40f6d31/Data/media/js/googleAnalyticsTag.js) to be used on cmip-publications.llnl.gov?

**Comment by durack1** [comment]
@mauzey1 yes please, that way we'll have all our PCMDI site stats in one place (minus CMEC, which I opened another issue about https://github.com/PCMDI/CMEC/issues/106)
