### ISSUE TITLE
Please add journal named: Frontiers in Earth Sciences

### ISSUE THREAD

**Issue by holtanova** [aims-group/publication-site#176]
**URL of journal's website**
https://www.frontiersin.org/journals/earth-science

**DOI of an article in the journal**
https://doi.org/10.3389/feart.2022.1018661

**Comment by taylor13** [comment]
@durack1 (Paul)
Do you have any concerns that this might be a "predatory" journal (without proper peer review)?  See https://en.wikipedia.org/wiki/Frontiers_Media .  If we think it is a predatory journal should we include it anyway?  I wonder if other journals we've approved are classified as predatory.
Karl

**Comment by durack1** [comment]
@taylor13 @mauzey1 I don't have a concern about this. I personally have published in [Frontiers in Marine Science](https://www.frontiersin.org/articles/10.3389/fmars.2019.00416/full) and am actively an editor in [Frontiers in Climate](https://www.frontiersin.org/journals/climate/sections/predictions-and-projections), so I think we're good here

**Comment by taylor13** [comment]
o.k., just checking.  I would note that the editorial board seems to include 1000's of scientists.  How does that work?
