### ISSUE TITLE
Please add journal named: <Forensic Science International: Reports>

### ISSUE THREAD

**Issue by JuliusStrack** [aims-group/publication-site#185]
**[URL of journal's website](https://www.sciencedirect.com/journal/forensic-science-international-reports)**

**[10.1016/j.fsir.2023.100321](https://doi.org/10.1016/j.fsir.2023.100321)**

**Comment by mauzey1** [comment]
@durack1 @taylor13  Should we add this journal?

**Comment by taylor13** [comment]
I guess it can't hurt.  Don't expect many articles will be published there though.  Let's wait on @durack1 to concur or object.

**Comment by durack1** [comment]
Also looks good to me; they used ScenarioMIP ssp585
