### ISSUE TITLE
viewing variables used in publication

### ISSUE THREAD

**Issue by taylor13** [aims-group/publication-site#189]
Sampling about 2 dozen of the CMIP6 registered publications and clicking on the "more info" button, I never see more than 4 columns of information: Activities, Experiments, Models, and Frequency.  Has no one entered "Realm" or "Variables" information, or are these not included in "more info"?

**Comment by mauzey1** [comment]
I think "Realm" and "Variables" were omitted from the "more info" section due to size constraints.  The website uses Bootstrap's responsive grid, which has a maximum width of 1170px for the site.  We could try customizing the width of the site to add more columns to the "more info" section.

**Comment by taylor13** [comment]
I guess the important thing is that the variables and realm information is in the database and a summary of how many papers use each can be obtained by clicking on the menu items at the right.  I'll close this.
