### ISSUE TITLE
Please add journal named: CATENA

### ISSUE THREAD

**Issue by subhankar17th** [aims-group/publication-site#190]
[**URL of journal's website**](https://www.sciencedirect.com/journal/catena)

[**DOI of an article in the journal**](https://doi.org/10.1016/j.catena.2023.107417)

**Comment by taylor13** [comment]
This looks legitimate to me.  Paul, see any red flags?
Karl

From: subhankar17th ***@***.***>
Reply-To: aims-group/publication-site ***@***.***>
Date: Wednesday, November 8, 2023 at 1:35 AM
To: aims-group/publication-site ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [aims-group/publication-site] Please add journal named: CATENA (Issue #190)


URL of journal's website<https://urldefense.us/v3/__https:/www.sciencedirect.com/journal/catena__;!!G2kpM7uM-TzIFchu!3bt7N-QlRhD0YCp1-r7No6OShOf33VPQmw4MTVwPS3KrsjWx4FhMubbyuvQGcJ_Zv8u2ZWOghhDESbTRuBFdwmPaOX0$>

DOI of an article in the journal<https://urldefense.us/v3/__https:/doi.org/10.1016/j.catena.2023.107417__;!!G2kpM7uM-TzIFchu!3bt7N-QlRhD0YCp1-r7No6OShOf33VPQmw4MTVwPS3KrsjWx4FhMubbyuvQGcJ_Zv8u2ZWOghhDESbTRuBFdXfCneMo$>
