### ISSUE TITLE
Please add journal named: Past Global Changes Magazine

### ISSUE THREAD

**Issue by jypeter** [aims-group/publication-site#200]
URL of journal's website: **[PAGES Magazine (Past Global Changes)](https://www.pastglobalchanges.org/publications/pages-magazines/pages-magazine)**

DOI of an article in the journal: **[Paleoclimate Modelling Intercomparison Project (PMIP): 30th anniversary](https://doi.org/10.22498/pages.29.2)**

**Comment by durack1** [comment]
Thanks @jypeter.

@mauzey1 this is another that should be added, when you have a minute to do so

**Comment by jypeter** [comment]
- @taylor13 I re-discovered the Publication Hub when googling "CMIP6 publications"!
 - and then found out that there was not that much PMIP-related content (quite an under-statement). But I also had #201 
 - so I thought I should maybe remind the PMIP community about this publication site
 - but I should try the submission process myself first, and I therefore created an account and tried to find out what I could submit
 - and then I ran into the _Journal is not referenced yet_ problem
 - about the _peer-reviewed publication_ question I first checked if there was an obvious FAQ or help or instructions at the top of the https://cmip-publications.llnl.gov/ page, but I did not find anything
