### ISSUE TITLE
Access the data directly

### ISSUE THREAD

**Issue by juliettelavoie** [aims-group/publication-site#211]
I was wondering under what format CMIP6 publication data is stored and if it is possible to have access to it directly. I would like to play with it programmatically instead of clicking through the website.

This could be interesting for cross-referencing in the Fresh Eyes data usage project.

Thanks !

**Comment by durack1** [comment]
Hi @juliettelavoie! This info is only a very small subset (1468 of 10's k publications), of the full CMIP5/6 suite of publications - for a ~1 month old snapshot of citation counts peek [here](https://nbviewer.org/github/durack1/MIPPlots/blob/main/CMIPCitationImpact.ipynb). We don't have this as an easily exportable format, but maybe could provide this, @mauzey1 would a database dump be much work?

**Comment by mauzey1** [comment]
You can get all of the publications listed on the site by going to the [search page](https://cmip-publications.llnl.gov/advanced_search) and pressing the `Show Bibtex` button near the bottom of the page.  Don't add or select any search info and you should get all of the entries on the site.  It will be in the bibtex format.

**Comment by juliettelavoie** [comment]
Thanks for the ressources @durack1 and @mauzey1 !

1) Just to confirm, the notebook is only showing the citations of papers describing cmip eras, CMIP6 MIPS and models, not from papers _using_ CMIP data ?
2) Where do you get the 10k publications number ? 
3) I saw the `show Bibtex` option but I was hoping to have access also to the "search data" (i.e. variables, frequency, MIP, source,...) for each entry .

**Comment by durack1** [comment]
> 1. Just to confirm, the notebook is only showing the citations of papers describing cmip eras, CMIP6 MIPS and models, not from papers _using_ CMIP data ?

In practice, folks who use the CMIP data most often cite the mip era protocol paper which describes the datasets, so for CMIP5 Taylor et al., 2012, and CMIP6 Eyring et al., 2016 - this is the 

```
...
Processing WoS: Taylor et al. 2012 <- web of science (WoS) totals, ~10k
Processing GS: KE Taylor et al. 2012 14893 <- google scholar (GS) totals
Processing WoS: Eyring et al. 2016 ~7k
Processing GS: V Eyring et al. 2016 7343
```

> 2\. Where do you get the 10k publications number ?

See above

For 3, not sure this will be all that useful, as these are user reported fields which are only filled for a small subset of the 1462 registered publications - this is far from a definitive resource

**Comment by juliettelavoie** [comment]
I see. Nevermind then. Thanks for the info!

**Comment by MartinaSt** [comment]
Just for completeness:
If you are looking for a specific data DOI, you can find papers citing the dataset in DataCite Commons, e.g. 
for doi https://doi.org/10.22033/ESGF/CMIP6.202 
https://commons.datacite.org/doi.org/10.22033/esgf/cmip6.202

We know that the information on papers citing data is incomplete for several reasons.

CMIP6 and input4MIPs data DOIs at DataCite Commons: https://commons.datacite.org/doi.org?query=client.uid%3Adkrz.esgf

**Comment by juliettelavoie** [comment]
Thanks!
