### ISSUE TITLE
Enhance search

### ISSUE THREAD

**Issue by James-Crean** [aims-group/publication-site#41]
When viewing pages other than 'All', search should be limited to the category the user was on when searching.

E.g. A search for year=2012 on the Experiment: 1pctCO2 page should limit results by both year and the experiment.

**Comment by mattben** [comment]
👍

**Comment by taylor13** [comment]
This indeed would be really cool.  I think *all* the search criteria that have been selected should appear at the top of the page of results.  

This sounds like a lot of work.  If so, perhaps the priority should be lower than most of the other "issues".
thanks.

**Comment by James-Crean** [comment]
With the addition of the advanced search, and the refactored 'view' pages, this should be considered complete.
