### ISSUE TITLE
AIMS Projects

### ISSUE THREAD

**Issue by mattben** [aims-group/publication-site#45]
under the project AIMS, we need Keywords

AIMS
PCMDI
CMIP
ARM
UV-CDAT
CDAT
vCDAT
ESGF
ACME
Python

**Comment by mauzey1** [comment]
@taylor13 @durack1  Since we are removing AIMS from the site, this issue is no longer relevant.

**Comment by durack1** [comment]
@mauzey1 you may want to check with @gabdulla as he may want the AIMS database stood up elsewhere - e.g. aims-publications.llnl.gov
