### ISSUE TITLE
URL Masking

### ISSUE THREAD

**Issue by mattben** [aims-group/publication-site#46]
we need a second url `publications.llnl.gov` then Project masking `publications.llnl.gov/cmip5` or `publications.llnl.gov/aims`
- /pcmdi
- /cmip
- /cmip3
- /cmip5
- /cmip6
- /aims

**Comment by durack1** [comment]
@mattben was there a question here, or is it just a placeholder for your reference?

**Comment by mattben** [comment]
@durack1 Just a task I need to complete

**Comment by James-Crean** [comment]
#56 Changes the url routes. For example instead of 
```
cmip-publications.llnl.gov/search?type=project&option=CMIP5
```
we will use
```
cmip-publications.llnl.gov/view/CMIP5/
```

**Comment by mauzey1** [comment]
This looks to be already completed.
