### ISSUE TITLE
Citation rule

### ISSUE THREAD

**Issue by mattben** [aims-group/publication-site#49]
all authors that are of 'ACME, PCMDI, AIMS, ... ' project should be bold faced.

**Comment by mauzey1** [comment]
@durack1 @taylor13  Do we still want this feature?

**Comment by durack1** [comment]
@mauzey1 how much work would it be? If we had a list of PCMDI/AIMS authors, so for e.g.

**Durack, Paul J.**, **Karl E. Taylor**, Veronika Eyring, **Sasha K. Ames**, **Tony Hoang**, **Denis Nadeau**, **Charles Doutriaux**, Martina Stockhause and **Peter J. Gleckler** (2018) Toward standardized data sets for climate model experimentation. Eos, Transactions, American Geophysical Union, 99. DOI: 10.1029/2018EO101751

If we had a PCMDI/AIMS team list:

Ames, Sasha Kando
Durack, Paul James
Taylor, Karl Erinodo
...

Could we regex these..

Actually @taylor13, thinking a little about this, as it's meant to be a site that lists all contributors, I'm not sure it makes sense to bold face PCMDI/AIMS folks?

**Comment by taylor13** [comment]
As Paul said, this site is now meant to serve the CMIP community, not our groups, so I think this feature should not be included.

**Comment by durack1** [comment]
Agreed, @mauzey1 I shall let you press the close button (as I can't). Oh how satisfying, squish
