### ISSUE TITLE
Views

### ISSUE THREAD

**Issue by mattben** [aims-group/publication-site#54]
The way pre defined search pages work will have to change once CMIP6 is added.

lets remove Model, Experiment, Variable, Frequency, and Keywords they should show up as options under there corresponding project.

![screen shot 2017-08-09 at 8 28 41 am](https://user-images.githubusercontent.com/438922/29130322-53bed11e-7cde-11e7-8b1b-ea7f216489ef.png)

**Comment by James-Crean** [comment]
Fixed in 30bc600
