### ISSUE TITLE
Password reset emails not being sent?

### ISSUE THREAD

**Issue by durack1** [aims-group/publication-site#65]
@James-Crean @mattben it seems that I am not receiving password reset emails - not sure this is working

**Comment by James-Crean** [comment]
Fixed using the llnl smtp relay server. Emails should now send, and should not get marked as spam generally.

**Comment by durack1** [comment]
@James-Crean did you want this tested?

**Comment by James-Crean** [comment]
Feel free to try it. I gave it a go myself and it worked.

**Comment by durack1** [comment]
@James-Crean yep, I can also confirm it worked, thanks!
