### ISSUE TITLE
Updates to CMIP6 page

### ISSUE THREAD

**Issue by durack1** [aims-group/publication-site#66]
A couple of tweaks would be great for the CMIP6 submission/new page.

Firstly, all the registered content/keywords that appear on the [search page](https://cmip-publications.llnl.gov/advanced_search) can be found in the [CMIP6_CVs repo](https://github.com/WCRP-CMIP/CMIP6_CVs).

Experiment: [CMIP6_experiment_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json)
Frequency: [CMIP6_frequency.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_frequency.json)
Model: [CMIP6_source_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json)
Variable: [Data Request - CMORvar](http://clipc-services.ceda.ac.uk/dreq/index/CMORvar.html) (This is managed external to LLNL)

Additionally, it would be great to include:
CMIP6 MIP: [CMIP6_activity_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_activity_id.json) (All experiments listed above are generally part of 1 or 2 sponsoring MIPs)
Realm: [CMIP6_realm.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_realm.json)

In particular for the use of the [IPCC Assessment Report 6 (AR6)](https://www.ipcc.ch/report/authors/report.authors.php?q=35&p=), having a relevant chapter to select would also be a useful search facet. The relevant chapters are:

| Chapter # | Title |
| :---: | -- |
| 1 | Framing, context, methods |
| 2 | Changing state of the climate system |
| 3 | Human influence on the climate system |
| 4 | Future global climate: scenario-based projections and near-term information |
| 5 | Global carbon and other biogeochemical cycles and feedbacks |
| 6 | Short-lived climate forcers |
| 7 | The Earth's energy budget, climate feedbacks, and climate sensitivity |
| 8 | Water cycle changes |
| 9 | Ocean, cryosphere, and sea level change |
| 10 | Linking global to regional climate change |
| 11 | Weather and climate extreme events in a changing climate |
| 12 | Climate change information for regional impact and for risk management |

@James-Crean ping

**Comment by taylor13** [comment]
I would note that the search categories available in CMIP5 should be different from those for CMIP6.  This implies several complications:

- The form filled out by users submitting a publication needs to be specialized (different), depending on project.
- The search facets displayed on the search page need to be different too, depending on project.

In both cases, we might consider a two-stage process:

1. stage 1: "Please select the CMIP phase that provided data for the publication"  (CMIP5, CMIP6, or CMIP5 & 6)
2. stage 2: The following instructions would appear: "Please refine your search"  (for the search page, where the search facets would depend on CMIP phase) or "Please provide information about the CMIP data analyzed by checking all appropriate boxes"  (on the publication submission page, with the facets again specialized to the CMIP phase.

If a publication uses both CMIP5 and CMIP6 data, I suggest the CMIP6 facets be displayed, but with the "Model" category including all CMIP5 and all CMIP6 models.   

We should also consider whether users might optionally include a list of "tracking_ids" or dataset  doi's used in their study.

**Comment by durack1** [comment]
@mauzey1 ping - this is the list we have been discussing

**Comment by durack1** [comment]
Convert Cmip5 and Cmip6 to uppercase (CMIP5 and CMIP6) as per:
![Screen Shot 2020-05-20 at 3 32 06 PM](https://user-images.githubusercontent.com/3229632/82503972-2a6d9380-9aaf-11ea-9fe7-1b4c092f9e63.png)

**Comment by durack1** [comment]
Also, it seems that the CMIP6 publications e.g Lyu, Kewei, Zhang, Xuebin, et al. (2020), Grise, Kevin M., Davis, Sean M. (2020) etc are being listed on the CMIP5 search page https://cmip-publications.llnl.gov/view/CMIP5/

**Comment by durack1** [comment]
Copying content of @MartinaSt from #91 below 

As follow up of this week's WIP telco, I open this issue to discuss possibilities to connect CMIP6 data references to this collection of CMIP6 papers.

A practical idea is:

    collect in the form information on DRS for the data including activity_id, experiment_id, source_id, institution_id
    get 'citation_url' from ESGF index using the DRS information from 1.
    resolve the citation_url and extract the data citation information from the JSON

This can run offline and does not need the provider to check for data references. Precondition is that the DRS components for an ESGF index request are complete.

@durack1 What do you think about this approach?

[Remark: On the long-run data users should cite CMIP6 data and the publishers should expose data references via the crossref api. As long as this ideal workflow remains broken in different steps, my suggestion provides an intermediate solution for linking data to articles.]

**Comment by durack1** [comment]
@MartinaSt in principle complete agreement, I would note however that by requesting `experiment_id` we already get the `activity_id` (other than in very few cases there are two sponsoring activities) and `source_id` also gives us `institution_id` (again with a few exceptions)

**Comment by MartinaSt** [comment]
@durack1 I am not sure if the request to the ESGF index (in 2.) will respond with more than one citation_url in these few cases. We should try it out, if it is not possible to extend the collected information in the pubsite by the missing DRS components.

**Comment by durack1** [comment]
@MartinaSt @mauzey1 is working on this as a second priority to the CMIP publication page. He has already generated the attached, and so we'll need to tweak this format to get to the finish line
[input4MIPs_report.json.txt](https://github.com/aims-group/publication-site/files/4854563/input4MIPs_report.json.txt)

**Comment by MartinaSt** [comment]
@durack1 @mauzey1 I might have missed something, but: why do you need my input for the format of your JSON? If you run a script adding CMIP6 data references to the CMIP6 (paper) publication page, this json is your internal format.

I have a comment and a question: 

- I would add the DOI resolver to the "doi" value. That makes life easier when exposing the DOI with a link. A CMIP6/input4MIPs data reference would have the form: 
 `<authors> (<publication year>) <title>. Earth System Grid Federation. <doi>.`
 My proposed usage of the "citation_url" in the ESGF index provides all this information.
- Do you use variable information collected from the user in your form for the list of datasets under "id"? 
This list might get quite long for CMIP6...

**Comment by durack1** [comment]
@MartinaSt apologies, this was posted in the wrong thread. It's the input4MIPs versioning issue https://github.com/PCMDI/input4MIPs-cmor-tables/issues/12, apologies will delete the above comment and migrate this to the correct issue
