### ISSUE TITLE
Link from "CMIP6: Terms of Use" to pubs page does not work

### ISSUE THREAD

**Issue by jypeter** [aims-group/publication-site#67]
The **link** from https://pcmdi.llnl.gov/CMIP6/TermsOfUse/TermsOfUse6-1.html

is https://cmip-publications.llnl.gov/search?type=project&option=CMIP6

and **does not work**

I think the one you want is https://cmip-publications.llnl.gov/view/CMIP6/

Btw, I don't see any CMIP6 publications, when we should have at least the GMD pubs. Is this due to a bug, or just because the GMD pubs have not been submitted yet?

Pinging @durack1 because I don't know who is in charge here if Matt has left

**Comment by durack1** [comment]
Thanks @jypeter that should now be fixed, not 100% certain about the CMIP6 existing publications, I suppose the GMD articles could be indexed, feel free to create yourself an account and start uploading, the DOI multiple load functionality should make the process much simpler this time around.

@taylor13

**Comment by durack1** [comment]
@James-Crean can you close this issue, it's now fixed by https://github.com/PCMDI/pcmdi.github.io/commit/7162d2da7b62215e057e40adde2c15b733fe2059
