### ISSUE TITLE
Publication count

### ISSUE THREAD

**Issue by taylor13** [aims-group/publication-site#68]
When you go to  https://cmip-publications.llnl.gov/view/CMIP6/ , the publication count =  1161  , which is the total across all projects (i.e., the same as what you see at https://cmip-publications.llnl.gov/ ).  I think the count should reflect the number for CMIP6 only.

**Comment by taylor13** [comment]
@mauzey1 @doutriaux1 @sashakames :  not sure whose responsibility this is, but there seem to be a couple of issues with the cmip-publications.llnl.gov service.  Besides the one listed above (which also should say that we only want to *list* the CMIP6 publications, not all the publications, when one selects CMIP6), and besides the issue listed in https://github.com/aims-group/publication-site/issues/69 and in  https://github.com/aims-group/publication-site/issues/70, there doesn't seem to be a way to add the additional information about experiments, variables, models, etc. that we had for CMIP5.  Maybe I need to provide some controlled vocabulary options???

**Comment by mauzey1** [comment]
@taylor13 @doutriaux1 @sashakames @durack1 
I have submitted a fix for this issue.  #71 
I currently don't have permission to select reviewers or merge for this repo so someone will need to approve and merge.

I will look into fixing #69.  #70 is just a copy of that issue; should we close it?

We should also look into updating this site to Django 2 and Python 3 to close #52.
