### ISSUE TITLE
reCAPTCHA v1 is no longer working on the new user registration page

### ISSUE THREAD

**Issue by mauzey1** [aims-group/publication-site#69]
https://cmip-publications.llnl.gov/accounts/register/

I am unable to create a new account due to reCAPTCHA v1 being shut down. 

https://developers.google.com/recaptcha/docs/faq#what-happens-to-recaptcha-v1

It will need to be upgraded to reCAPTCHA v2.

**Comment by durack1** [comment]
@mauzey1 thanks for testing this out!
