### ISSUE TITLE
DOI search no longer appears to be working

### ISSUE THREAD

**Issue by durack1** [aims-group/publication-site#79]
@mauzey1 I was just taking a look at the publication site today with @gabdulla. I tried using the DOI autopopulate functionality on the https://cmip-publications.llnl.gov/new page and it doesn't seem to be working.

Is this an easy fix?

Also, if we were to advertise this widely, with an expectation that we could have ~100 new users in a relatively short period of time, are we in good shape to support them (bug fixes, and account issues) in the coming months?

**Comment by mauzey1** [comment]
I will look into this issue.

I would like to update the site to use Python 3 and Django 2 at some point.  I could start on that this week.

**Comment by durack1** [comment]
@mauzey1 sounds good to me, what kind of time would you expect that upgrade to take? Is it a weeks worth of work would you guess?

**Comment by mauzey1** [comment]
Yes, I think it would take about a week of work to get the Python 3/Django 2 update into production.

**Comment by durack1** [comment]
@mauzey1 that would be great, if @taylor13 and @gabdulla have nothing else more pressing, then yes please do get this fix and upgrade done

**Comment by gabdulla** [comment]
Nothing more pressing from my side.

Ghaleb

**Comment by durack1** [comment]
@mauzey1, Ive just received another query about using this site and was wondering where these tweaks and updates are in the queue?

**Comment by mauzey1** [comment]
@durack1 @gabdulla 
I plan to push the updates for Python3/Django2 into the production server sometime this week.  We should plan a day for site downtime for performing the update.  This should take 1-2 hours.

After completing the update, I plan to investigate the DOI search issue.  This might require the help of @taylor13 and @sashakames.

**Comment by taylor13** [comment]
glad to help.  Thanks!

**Comment by durack1** [comment]
@mauzey1 sounds great. With the DOI issue, if I recall correctly there was a problem previously with certificates, I may have got that wrong, but if @James-Crean's memory is intact, he might be able to provide a little guidance here

**Comment by James-Crean** [comment]
Hard to say for sure without looking at the logs, but I would guess you are correct Paul. 
Likely you just need to tell requests to use the correct cert file. Something like this would probably work:
```python
requests.get('https://github.com', verify='/path/to/certfile')
```
Bonus points if you use a Django settings variable instead of a hard coded string. Would make development/deployment easier.

More reading available here: https://requests.readthedocs.io/en/v3.0.0/user/advanced/

**Comment by durack1** [comment]
@James-Crean hero, thanks for the pointer!

I hope 2020 has kick off well for you in the South Bay. Thanks again.

**Comment by mauzey1** [comment]
@durack1 @James-Crean Yes, the problem is due to the CA certificate for the server not being used by requests.  On my workstation, I was able to use the certificate by assigning the `REQUESTS_CA_BUNDLE` environment variable to its path.  I was having difficulties applying the same change in the server even though the necessary certificate should be present.

**Comment by mauzey1** [comment]
@durack1 @gabdulla I fixed the issue with DOI search.  There was a CA certificate missing from the system's CA bundle file.  I have updated this file, restarted Apache, and the DOI search now works.

**Comment by taylor13** [comment]
I tried it out and submitted a publication.  It worked perfectly!
thanks!

**Comment by durack1** [comment]
@mauzey1 champion! Is the Django 3 update also in the queue, or has that also been completed?

**Comment by mauzey1** [comment]
@durack1 I still plan to do the Django 3 update.  I plan to do the update next Wednesday in the afternoon.  We might want to put up a maintenance banner for that time.
