### ISSUE TITLE
Possibility to add CMIP6 data references

### ISSUE THREAD

**Issue by MartinaSt** [aims-group/publication-site#91]
As follow up of this week's WIP telco, I open this issue to discuss possibilities to connect CMIP6 data references to this collection of CMIP6 papers.

A practical idea is:

1.  collect in the form information on DRS for the data including activity_id, experiment_id, source_id, institution_id
2.  get 'citation_url' from ESGF index using the DRS information from 1.
3.  resolve the citation_url and extract the data citation information from the JSON

This can run offline and does not need the provider to check for data references. Precondition is that the DRS components for an ESGF index request are complete.

@durack1 What do you think about this approach?

[Remark: On the long-run data users should cite CMIP6 data and the publishers should expose data references via the crossref api. As long as this ideal workflow remains broken in different steps, my suggestion provides an intermediate solution for linking data to articles.]

**Comment by durack1** [comment]
Content above copied into https://github.com/aims-group/publication-site/issues/66#issuecomment-646296481

@mauzey1 please close
