### ISSUE TITLE
Treatment of journals missing from our list

### ISSUE THREAD

**Issue by taylor13** [aims-group/publication-site#92]
I just entered a "test" article and noticed this problem:  The journal "Science Advances" is not one we have in our search list. It seems that my only choice was to enter "other".  It would be better if:
1) a user enters the doi (as I did), we simply add the returned journal name to our list of acceptable journal names, or if it is difficult to update the list of journals in our list,  could we at least put the actual journal name (returned by the doi) in the reference.  My article appears as being published in a journal named "other".
2) If the user has not used the "doi option" to obtain the citation information but instead is manually entering the information, could we allow him/her to enter a journal name not in our recognized list?

Alternatively, if the name isn't in our list, maybe we could ask the user to submit a request that the journal name be added.  What do you think @durack1 ?

**Comment by durack1** [comment]
👍

**Comment by durack1** [comment]
@mauzey1 it would be great if any journal entry that is obtained by a valid DOI search, is added to our list. I can forsee situations where a paper has been submitted (but not yet published) and a user would want to enter this paper in process into the database. They would then hopefully update the entry once their paper is published, and in this case may need to add a DOI after an entry is already in place.

Can the system accomodate such a situation?

**Comment by mauzey1** [comment]
@durack1 Yes, I think we can update the database with journals from valid DOI links if they are not already present in the database.

**Comment by durack1** [comment]
Thanks @mauzey1. In the case that there is no valid DOI, so it is a submitted rather than published paper, we would want users to submit the details, but maybe we'd want to approve a new entry before automatically adding it - is this possible? And if yes, would it take alot of work/time?

**Comment by mauzey1** [comment]
Could we just get rid of the list of journals and have users submit the title of the journal either manually in the form, or automatically from the DOI?  I've noticed other publication sources such as conferences and magazine just have you enter a name.

If we want users to submit a new journal to be added to this list, then I think we should have a separate section for submitting new journals.  I think we should approve the addition of a new journal rather than have it automatically added.  Or we could just have users submit a GitHub issue, or email us, about listing a journal currently not on list.

**Comment by durack1** [comment]
@taylor13 I would not submit a conference proceedings/abstract here, just published papers, we should probably reduce this to publications only, and peer-reviewed, right?

**Comment by taylor13** [comment]
regarding https://github.com/aims-group/publication-site/issues/92#issuecomment-659017488, I agree.  What would you include?  Just Journal articles and Books?  Also, I assume we wouldn't require a journal article to have been accepted, only submitted, right?

Regarding https://github.com/aims-group/publication-site/issues/92#issuecomment-659015924, the doi is the preferred (and, if available, the easiest) route, but for articles not yet assigned a DOI, I think the list is better than asking the user to enter text because it ensures accuracy.  Even if we allow text, wouldn't we want to check the entry against some master list of official journal names?  

So, how would a user enter a journal name not on the list?  Following one of your options, I think the easiest thing to do if the user selects "other" (in the journal selection menu) is to pop up (or expose) a message that would say something like:  "If the journal publishing your article is not on the list, please submit an issue at https://github.com/aims-group/publication-site/issues/ with subject title: 'Please add journal named: NAME OF JOURNAL.'  Thank you.".

Other suggestions?

**Comment by taylor13** [comment]
Another option on requesting the addition of a journal, we could simply ask them to enter the journal name; then it could be emailed to someone who would be responsible for adding it to the publication website.  I guess that's where we could get into trouble if there are lots of requests (which I wouldn't expect).  Chris (or someone) would have to update the publication submission form each time a request came in.  Would that take much time?  (10 minutes, an hour, a half day???)  We don't want this to become a lot of trouble to maintain.  Do we know how many journal articles are in the CMIP5 database that have journal name = "other"?

**Comment by mauzey1** [comment]
@taylor13 Adding new journals to the list will not be hard or take long.  It would just require updating [scripts/journals.py](https://github.com/aims-group/publication-site/blob/master/scripts/journals.py), and updating the site's database with `python manage.py makemigrations`, or adding the journal name(s) to the database in the Django admin page.

**Comment by mauzey1** [comment]
Currently, the site will try to guess the title in the list of journals that most closely matches the journal title from the DOI search.  I think we should either find the exact match of the title in the journal, or ask the user to submit an issue to add the journal if it is not found in the list.

Below are screenshots of an example of submitting an article from a journal that is not listed.

Here is a message added to the journal section of the submission page asking users to send issues to GitHub if their article's journal is not listed.
![pub_before_doisearch](https://user-images.githubusercontent.com/42009431/94505713-8dd7a280-01c0-11eb-8bf9-2f8518492721.png)

Here is the warning message that appears when the journal name from the DOI search is not found in the journal list.  The journal title defaults to "Other" if not found.
![pub_after_doisearch](https://user-images.githubusercontent.com/42009431/94505785-b6f83300-01c0-11eb-8818-536f4fb9b3c3.png)

**Comment by taylor13** [comment]
This looks like a really good fix.  Thanks.  Just to check one thing ... Where is the warning message displayed?  When the user enters the DOI, will he/she have to scroll down to see the error message?  That's o.k. if there is some flag at the top of the page indicating that the entry wasn't entirely satisfactory.
Also, I think to give the user added incentive, you might add a sentence to the warning saying something like "Currently, your publication will be entered with journal set to "other"."  
Should we also suggest that once the Journal has been added, the user will have to edit their publication correcting the journal name?  Or do you think that is too much text??

**Comment by mauzey1** [comment]
@taylor13 I could move the warning message from the publication selection section to the top of the form under the message for required fields.  I will also add that message about the journal being set to "other" as default, and add a message that you can edit the entry later when the journal is added.

**Comment by taylor13** [comment]
Great.  Thanks.

**Comment by mauzey1** [comment]
Here is the new warning message that will appear above the form after the DOI search.
![Screenshot_2020-09-29 New Publication](https://user-images.githubusercontent.com/42009431/94630885-def89c80-027b-11eb-9a77-4bdb5f2993ea.png)

**Comment by taylor13** [comment]
Thanks that's fine.  I suggest a slight rewording of the second paragraph:
```
Currently, your publication will be registered with journal set to "Other".  Once you've submitted the issue, 
as described above, and the journal name you requested has been added to the list, please go to the Edit 
page, select your publication, and replace "Other" with the actual name of the journal. 
```

**Comment by mauzey1** [comment]
@taylor13 @durack1 

Here is the warning message with the updated second paragraph.
![Screenshot_2020-09-30 New Publication](https://user-images.githubusercontent.com/42009431/94754278-a7eebd80-0345-11eb-9ac9-3a3767aed3ef.png)

These changes have now been applied to the test server.  If you are satisfied with these changes, then we can close this issue.  These changes should also resolve issue #103 since we avoid trying to guess which journal in the list matches the journal from the DOI, and instead just asks the user to submit a journal title to us via GitHub.

**Comment by taylor13** [comment]
Agreed.  Thanks!

**Comment by durack1** [comment]
@mauzey1 agreed, this looks perfect
