### ISSUE TITLE
citation anomalous page numbers appear. 

### ISSUE THREAD

**Issue by taylor13** [aims-group/publication-site#93]
This is very low priority, I think.

the journal Science Advances recommends the citation for the paper I just entered in the database should be:
```
Science Advances  24 Jun 2020:
Vol. 6, no. 26, eaba1981
DOI: 10.1126/sciadv.aba1981 
```

I have no idea why "eaba1981" is given as part of the citation.  When I entered the doi, "eaba1981" got returned as the "page number" and in our publication-site it appears that the page numbers are:  eaba1981 - eaba1981.  Maybe this is o.k. but it looks funny to me.  @durack1 :  Any idea whether this is a new approach to numbering pages in non-print journals?

**Comment by durack1** [comment]
Yeah that isn't unique to [Science Advances](https://advances.sciencemag.org/), for Environmental Research Letters they also have a non-page number identifier, so for e.g. [Durack et al., 2014 ERL](https://doi.org/10.1088/1748-9326/9/11/114017). Maybe the preceding "e" in front of the rest of the doi "aba1981" indicated e-print only or similar?

**Comment by taylor13** [comment]
Maybe we could handle this a little more elegantly so that it doesn't appear as "eaba1981-eaba1981", but rather as simply "eaba1981".  It's not clear to me what is actually returned from the web when we ask for the citation information, but what appears in our website form is "Start page: eaba1981" and "End page: eab1981".  Could we check that if the "end page" is anything but an integer, then we set end page to null, and in the subsequent display of the citation, if the "end page" is missing omit the hyphen following the "start page"?

@durack1  can you think of any citations where that would be inappropriate?

**Comment by durack1** [comment]
@taylor13 we could load up the demo site with the two examples (as noted above, plus the Science Advances: https://doi.org/10.1126/sciadv.aba1981 and hope that it covers most cases?

**Comment by taylor13** [comment]
I've already added a couple of entries on the test site (which is how I'm identifying any problems).

**Comment by durack1** [comment]
@taylor13 this is another candidate, Nature Communications which is online only, but interestingly has integer identifiers which differs from others, e.g. https://doi.org/10.1038/s41467-018-05634-2

**Comment by taylor13** [comment]
@mauzey1 Any progress on this?

**Comment by mauzey1** [comment]
@taylor13 I haven't started on this, yet.  I will start working on this issue after resolving #103.

**Comment by mauzey1** [comment]
The code responsible for setting the start and end page numbers are here:
https://github.com/aims-group/publication-site/blob/6e55027bf6c4cf2b5313f852be957de977a28e9d/apps/publisher/views.py#L869-L876
If only one page number is detected, if the value in the attribute `page` of the DOI info doesn't have a dash, then it will set the start and end pages as the same value.  The template for the citation can already omit the dash if the end page is set to `None`, and the BibTex section will also not display the pages if the end page is missing.  This can be accomplished by having `endpage = None` for the exception.

**Comment by taylor13** [comment]
looks good.  Thanks.

**Comment by mauzey1** [comment]
I will close this issue now since I have already added the changes mentioned in https://github.com/aims-group/publication-site/issues/93#issuecomment-689240572 to the testing branch at https://github.com/mauzey1/publication-site/commit/d1b79476a89c56f479aa1999370df09c05a8e0ab.
