### ISSUE TITLE
Make "Project" selection mandatory.

### ISSUE THREAD

**Issue by taylor13** [aims-group/publication-site#95]
When submitting an article to the database, the user is supposed to select a project (CMIP5, CMIP6, or both). This should be mandatory.  Currently it seems to be optional.  If the user tries to submit without checking at least one of the boxes under "project" they should see an error message indicating: "Under "Project", you must make a selection before submitting."

**Comment by durack1** [comment]
@taylor13 for some of the science that I have in mind, I'd also want to use CMIP3 data. As it exists, would it be useful to add CMIP3 in as a project alongside CMIP5/6?

I realise the horse has bolted back in the 00's to capture CMIP3-only publications, but just thinking ahead

**Comment by taylor13** [comment]
Yes, I think this is probably a good idea, but let's wait on this addition (of CMIP3) until after we launch the CMIP5 & 6 version, which we'd like to do as soon as it's ready.

**Comment by durack1** [comment]
I wonder while we're at it, if "CMIP1/2" is also warranted? I have a single case that will be using this data (once I pull it out of archives and get it rewritten), and I know that the PMP outputs are also targeting this data. That would cover our bases, aside from AMIP1 and AMIP2

**Comment by taylor13** [comment]
I agree; but not for our first updated release.  We'll have to think about facets and so on.

**Comment by durack1** [comment]
@taylor13 true, I have started work on the [CMIP2_CVs](https://github.com/durack1/CMIP2_CVs) it'd make sense to do this for 3 and 5, as I will need such information for the forcing tables I intended to generate for the input4MIPs GMD publication

**Comment by mauzey1** [comment]
@durack1 @taylor13 I have added a change to the publication site that will make selecting at least one project a requirement for submission.  If you try to submit without selecting a project, the submission page will reload with the following for "Projects".
![Screenshot_2020-08-11 edit](https://user-images.githubusercontent.com/42009431/89952252-bf30ea80-dbe1-11ea-8bc9-95f517c6a346.png)

**Comment by taylor13** [comment]
Excellent!  thanks for that.
Karl

**Comment by taylor13** [comment]
I think it would be even better if there were some indication at the top of the page when the error is encountered.  When I "forgot" to check one of the project boxes, it wasn't obvious to me that I had to do anything.  Some users might think they were successful.  We could post the message at the *top* of the page so it was obvious.  Something like:  "Error -- Missing required information: Please scroll down and select at least one of the projects."

I also noticed that when a user returns to edit a submission, none of their selections for activity, model, frequency, etc. is remembered.  If the user has spent a lot of time selecting these the first time around, but forgot one model, for example, it would be frustrating to reenter *all* the models and all the other categories again.  Can the selected items be retained (i.e., check marks included), when a user goes back to edit a publication?

**Comment by mauzey1** [comment]
We should also add a message at the top of the form that indicates that fields with a `*` next to them are required.

When you say "a user goes back to edit a publication" do you mean when they go back to the submission page when they forget a required field after clicking "submit", or when they go to the "edit" page to change their previous submissions?

When creating a new publication, I checked facets for one of the models but didn't have a date.  This caused me to go back to the submission page since I have forgotten a required field.  The checked facets were still checked.  They should also still be checked in the edit page after the submission is successful.

**Comment by taylor13** [comment]
ok I'll check again tomorrow, and let you know.  Maybe I got it wrong.  

I second the "required" message.

**Comment by durack1** [comment]
@mauzey1 thanks for this, I will take a try myself this afternoon to see how close we're getting

**Comment by taylor13** [comment]
After checking what I did yesterday, I think you're right.  It retains memory of all checked boxes.  Looking good!  thanks.

**Comment by taylor13** [comment]
I think the message about required fields isn't noticeable enough (and could also be a bit more directive).  Here's what some users will do:  enter a doi, then scroll down not noticing that "project" hasn't been selected, then hit "submit".  The form jumps back to the top, but doesn't indicate that they weren't successful in their submission.    Perhaps we could prevent problems if the font is colored red and the message is changed to:  "Required information, marked by an "*", is missing below."     
A new user won't know that the sign of success is that the form disappears and is replaced by a listing of the user's publications. 
There's probably other options too.  The above is one suggestion.
thanks.

**Comment by mauzey1** [comment]
@taylor13 I have added a new message that comes up if you have missing required fields in your submission form.
![Screenshot_2020-08-24 New Publication](https://user-images.githubusercontent.com/42009431/91103431-50f81900-e620-11ea-9f22-b1102829d31b.png)

**Comment by taylor13** [comment]
Excellent.  Thanks.  I think we can close this issue.
