### ISSUE TITLE
when editing a publication, dataset descriptive identifiers missing

### ISSUE THREAD

**Issue by taylor13** [aims-group/publication-site#96]
(This is low priority).

I went back to edit an article that I had entered into the data base, and found that although I had already identified the publication as belonging to the CMIP6 project, there were no facets shown (i.e., no activities, sources, frequencies etc.  listed). I didn't notice at first the tabs that allow you to get the lists to be populated.   This is not a show-stopper.

**Comment by taylor13** [comment]
Here's a bit more information:  On the test site I submitted a publication titled "Documenting numerical experiments in support of the Coupled Model Intercomparison Project Phase 6 (CMIP6)" and indicated it was part of CMIP6 (but I don't think I selected any facets). It was registered in the database.  Then I went back to edit this entry and it when I scrolled down to select "activity", none were showing.  I think displayed were the facets for CMIP5, which doesn't have an activity list.  The page indicated that CMIP6 had been selected for project (which is correct), and a single tab over the facets said "CMIP6", but I had to click on that tab to get it to display the CMIP6 facets.  It would be better, as a default, for it to have displayed the facets for the project selected (CMIP6 in this case).

**Comment by mfwehner** [comment]
I see the same issue. I used CMIP5 and CMIP6. If I check CMIP5 first, I can enter in the CMIP5 stuff but not CMIP6. If I check CMIP6 first, I can't enter either.

**Comment by taylor13** [comment]
I'm testing our non-public site.  
I can't remember whether we already discussed this use case.  How should we handle articles that use both CMIP5 and CMIP6 data?  It looks like we can list these articles by clicking both the CMIP5 and CMIP6 projects.   That's good. Then we get two tabs ("CMIP5" and "CMIP6") for selecting the model/experiment/data information.  If you enter the CMIP5 information, then click on the CMIP6 tab and enter the CMIP6 information, and then submit your article, you lose the CMIP5 information.  What's odd is, that if you then go back and edit that article information, and reenter the CMIP5 information, and resubmit, then you successfully record everything.  If possible, the original submission should behave like an edited submission and show both CMIP5 and CMIP6 model/experiment/data information (i.e., not lose the CMIP5 information).

**Comment by taylor13** [comment]
This may be somewhat related to issue https://github.com/aims-group/publication-site/issues/97

**Comment by mauzey1** [comment]
@taylor13 I have added changes to the non-public test branch that solves the issue of CMIP5 information not being saved after submission.  The submission should now save the information of all selected projects.

**Comment by taylor13** [comment]
Thanks @mauzey1 !  I've confirmed it's now working.   I'll close this.
